### ISSUE TITLE
Const in object assign is causing Uglify to broke

### ISSUE THREAD

**Issue by LucaDb** [o2team/elf-preloader.js#4]
The last version 1.2.0 has a "const" declaration in the built js file (src/js/preloader.js).
This is causing uglify to broke.

GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: keyword (const)

**Comment by booxood** [comment]
@LucaDb My mistake. Please upgrade to v1.2.2 .
